pairs:
  - [1456173014931603456, 1429879717284151398]   # LN ↔ AI
  #- [1456173014931603456, 1422925057339953182]   # LN ↔ AI
  
  #- [1456173014931603456, 1468649165109203177]   # LN ↔ TestServer
  #- [1429879717284151398, 1468649165109203177]   # AI ↔ TestServer

receivers:
  - 1468498093115969566   # Triad
  - 1468649165109203177   # TestServer

allowed_users:
  - 404287153213014038     # shnnn
  - 433607960493555722     # James